In [2]:
import numpy as np
import rand as rand

In [3]:
import pathlib
from pathlib import Path
list(Path(".").iterdir())
from PIL import Image, ImageOps


In [4]:
import tarfile
tar = tarfile.open("kkanji.tar") # Open for reading with gzip compression.
tar.extractall()
tar.close


<bound method TarFile.close of <tarfile.TarFile object at 0x000002174B46EA90>>

In [15]:

imgs = np.zeros((64,64), np.uint8).reshape(1,64,64) #Dummy black image to setup the ndarray
labels = np.array(['XXX'])

for folder in Path("kkanji2").iterdir():
    label = folder.__str__().split("\\")[1]
    for kanji_path in folder.iterdir():
        image = np.array(Image.open(kanji_path)).reshape(1,64,64)
        imgs = np.concatenate([imgs,image])
        labels = np.concatenate([labels,np.array([label])])

imgs = np.delete(imgs,0,0)
labels = np.delete(labels,0,0)

U+241C6
U+24FA3
U+25DA1
U+27752
U+29780
U+29DDA
U+29E75
U+4093
U+4453
U+4543
U+4572
U+4C61
U+4C99
U+4E00
U+4E01
U+4E03
U+4E07
U+4E08
U+4E09
U+4E0A
U+4E0B
U+4E0D
U+4E0E
U+4E11
U+4E14
U+4E16
U+4E17
U+4E18
U+4E19
U+4E1E
U+4E21
U+4E26
U+4E2D
U+4E32
U+4E38
U+4E39
U+4E3B
U+4E3C
U+4E42
U+4E43
U+4E45
U+4E4B
U+4E4D
U+4E4E
U+4E4F
U+4E57
U+4E58
U+4E59
U+4E5D
U+4E5E
U+4E5F
U+4E71
U+4E73
U+4E7E
U+4E80
U+4E82
U+4E86
U+4E88
U+4E89
U+4E8B
U+4E8C
U+4E8E
U+4E91
U+4E92
U+4E94
U+4E95
U+4E98
U+4E99
U+4E9B
U+4EA1
U+4EA4
U+4EA5
U+4EA6
U+4EA8
U+4EAB
U+4EAC
U+4EAD
U+4EAE
U+4EBA
U+4EC0
U+4EC1
U+4EC2
U+4EC7
U+4ECA
U+4ECB
U+4ECD
U+4ECF
U+4ED4
U+4ED5
U+4ED6
U+4ED8
U+4ED9
U+4EDD
U+4EE3
U+4EE4
U+4EE5
U+4EED
U+4EEE
U+4EF0
U+4EF2
U+4EF6
U+4EFB
U+4F0A
U+4F0D
U+4F0F
U+4F10
U+4F11
U+4F1A
U+4F1D
U+4F2F
U+4F34
U+4F38
U+4F3A
U+4F3C
U+4F3D
U+4F46
U+4F47
U+4F4D
U+4F4E
U+4F4F
U+4F50
U+4F53
U+4F55
U+4F59
U+4F5B
U+4F5C
U+4F69
U+4F73
U+4F75
U+4F76
U+4F7F
U+4F86
U+4F8B
U+4F8D
U+4F98
U+4F9B
U+4F9D
U+4FA0
U+4FAD
U+4FAE
U+4FAF
U+4FB2

In [24]:
np.savez_compressed('kkanj-imgs.npz', imgs)
np.savez_compressed('kkanji-labels.npz', labels)

In [3]:
# Load the .npz file
data_imgs = np.load('kkanj-imgs.npz')
data_labels = np.load('kkanji-labels.npz')

# Access the arrays stored in the .npz files
imgs = data_imgs['arr_0']
labels = data_labels['arr_0']

# Perform operations on the loaded data
print("Shape of imgs:", imgs.shape)
print("Shape of labels:", labels.shape)



num_elements_to_print = 5
print("First", num_elements_to_print, "elements in imgs:")
print(imgs[:num_elements_to_print])


num_elements_to_print = 5
print("First", num_elements_to_print, "elements in labels:")
print(labels[:num_elements_to_print])






Shape of imgs: (140424, 64, 64)
Shape of labels: (140424,)
First 5 elements in imgs:
[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...  25   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ... 157  18   0]
  [  0   0   0 ...  16   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   